language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      env: TOX_ENV=lint
      install: pip install --upgrade flake8
      script: make test-lint
    - python: 3.7
      dist: xenial
      env: TOX_ENV=static-type-checks
      install:
        - pip install --upgrade pytype
        - pip install -r requirements.txt
      script: make test-type-check
    - python: 3.5
      env: TOX_ENV=py35
      install: pip install --upgrade tox pytest
      script: tox -e $TOX_ENV
    - python: 3.6
      env: TOX_ENV=py36
      install: pip install --upgrade tox pytest
      script: tox -e $TOX_ENV
    - python: 3.7
      env: TOX_ENV=py37
      install: pip install --upgrade tox pytest
      dist: xenial
      script: tox -e $TOX_ENV

notifications:
  email: false